"""empty message

Revision ID: 98abff08f972
Revises: 5ebffc563824
Create Date: 2022-03-30 14:22:36.046776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98abff08f972'
down_revision = '5ebffc563824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    op.alter_column('property', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('property', 'longitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('property', 'latitude',
               existing_type=sa.Float(precision=20),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
